name: River House
tagline: A new wave of Grade A office and retail space in the heart of Belfast’s Cathedral Quarter.
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

email: rpittaway@castleforgepartners.com

website: http://riverhousebelfast.co.uk

imageurl: /images/

permalink: pretty

#baseurl: https://riverhousebelfast.co.uk
url: https://riverhousebelfast.co.uk

googlemaps: https://www.google.com/maps/dir//River+House+48-60+High+St/@54.600485,-5.9964596,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x4861090aab6d02d3:0x2fe7716f8d70ed18!2m2!1d-5.92642!2d54.6004058


gems:
  - jekyll-sitemap

# Navigation
navigation:
  - title: Home
    url: //riverhousebelfast.co.uk/
  - title: Building
    url: /building/
  - title: History
    url: /history/
  - title: Location
    url: /location/
  - title: Clockwise
    url: /clockwise/
  - title: Contact us
    url: /contact/
  # - title: Downloads
  #   url: /downloads/

features:
  - name: Generous double-height in reception area(s)
  - name: New High-Rise glazed Curtain Wall System
  - name: Raised access flooring
  - name: Car park
  - name: 6,000 sq ft. floorplates
  - name: Onsite cafe
  - name: Generous bike storage space
  - name: Multiple high-speed data networks
  - name: Excellent natural light

floorspace:
  - floor: Ground Floor Unit 1/2
    sqm: 218
    sqf: 2,347
  - floor: Ground Floor Unit 3
    sqm: 106
    sqf: 1,140
  - floor: Ground Floor Unit 4 - LEASED
    sqm: 
    sqf: 
  - floor: Ground Floor Unit 5
    sqm: 120
    sqf: 1,292

offices:
  - floor: 1st Floor - Clockwise Cafe & Reception	 
    sqm: 
    sqf: 
  - floor: 2nd Floor - Clockwise Roof Terrace
    sqm: 
    sqf: 
  - floor: 3rd Floor - Clockwise Serviced Office
    sqm: 550
    sqf: 6,000
  - floor: 4th Floor - Clockwise Serviced Office
    sqm: 550
    sqf: 6,000
  - floor: 5th Floor - Clockwise Serviced Office
    sqm: 550
    sqf: 6,000
  - floor: 6th Floor
    sqm: 550
    sqf: 6,000
  - floor: 7th Floor
    sqm: 550
    sqf: 6,000
  - floor: 8th Floor
    sqm: 550
    sqf: 6,000
  - floor: 9th Floor
    sqm: 550
    sqf: 6,000
  - floor: 10th Floor
    sqm: 550
    sqf: 6,000
  - floor: 11th Floor
    sqm: 550
    sqf: 6,000
  - floor: 12th Floor
    sqm: 550
    sqf: 6,000
  - floor: 13th Floor - LEASED
    sqm: 
    sqf:
  - floor: 14th Floor - LEASED
    sqm: 
    sqf:

downloads:
  - name: River House Brochure
    link: riverhousebrochure.pdf
  - name: Specification Sheets
    link: specsheets.pdf
  - name: Floor Plans
    link: floorplans.pdf
  - name: DWG Files
    link: dwg-files.zip

team:
  - name: Adrian Poucher – Malcolm Hollis LLP
    title: Project Manager
  - name: John Lee – Povall Worthington
    title: Architect
  - name: Michael Riordan – Linesight
    title: Cost Consultant
  - name: Thomas Lehd – Lehding Services Design
    title: M&E Engineers
  - name: Christopher Reynolds – Brian W Murray
    title: Structural Engineers
  - name: Tony McParland – Jeremy Gardner Associates
    title: Fire Engineers
  - name: Paul Cheyne – Hasco Europe
    title: Principle Designer
  - name: MAC Group
    title: Principle Contractor

timeline:
  - date: 1600s
    description: Once occupied by docks of the Merchant City, River House is at the heart of Belfast’s unique history.
  - date: 1790s
    description: The United Irishmen met under the guise of "The Muddlers Club" at Peggy Barclays Tavern in Sugarhouse Entry. The tavern is long gone but the entry is still there beside River House.
  - date: 1804
    description: The River Farset culverted to create High St. It still flows underneath to this day.
  - date: 1816
    description: With the new church of St Anne full to bursting, a new church, St Georges, is erected on High Street, opposite where River House now sits.
  - date: 1967
    description: The River House Office building undergoes development. The end result sees Waring and Skipper Streets connected.
  - date: 2012
    description: Belfast’s Metropolitan Arts Centre (The MAC) opens at St Anne’s Square in Cathedral Quarter, bringing further life to an already vibrant location.
  - date: 2015
    description: Belfast Bikes are introduced across the city. Over 191,000 journeys increasing by 27% each year.
  - date: 2017
    description: Located directly in front of River House, work commences on Belfast Cycle Network, involving major alterations and cycle way upgrades.
  - date: 2018
    description: The development of River House is completed in Q4, offering 80,000 sq ft of office and retail space over 13 floors.


charity-facebook: https://www.facebook.com/riverhouseyard/

charity-twitter: https://twitter.com/caudwellkids?lang=en

charity-instagram: https://www.instagram.com/caudwellchildren/

charity-register: https://www.eventbrite.co.uk/e/climb-for-caudwell-children-tickets-36687495286

charity-donate: https://www.eventbrite.co.uk/e/climb-for-caudwell-children-tickets-37337004987#tickets

facebook: https://www.facebook.com/riverhousebelfast/
twitter: https://twitter.com/RHBelfast
instagram: https://www.instagram.com/riverhousebelfast/
linkedin: https://www.linkedin.com/company/riverhousebelfast/